#ifndef RSLALGORITHMS_GLOBAL_H
#define RSLALGORITHMS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RSLALGORITHMS_LIBRARY)
#  define RSLALGORITHMSSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RSLALGORITHMSSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RSLALGORITHMS_GLOBAL_H
