#ifndef RSLSEQUENCES_GLOBAL_H
#define RSLSEQUENCES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(RSLSEQUENCES_LIBRARY)
#  define RSLSEQUENCESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define RSLSEQUENCESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // RSLSEQUENCES_GLOBAL_H
